services:
  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: gigalogy_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - gigalogy

  nginx:
    image: nginx:stable
    container_name: gigalogy_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gigalogy

  db:
    image: postgres:15
    container_name: gigalogy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gigalogy

  worker:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: gigalogy_worker
    restart: unless-stopped
    depends_on:
      - app
      - db
    volumes:
      - ./:/var/www
    command: ["php", "artisan", "queue:work", "--sleep=3", "--tries=3"]
    networks:
      - gigalogy

volumes:
  dbdata:

networks:
  gigalogy:
    driver: bridge
